import CategoryService from "./Category";
import SessionService from "./Session";
import OpenIdService from "./OpenId";
import ShopsService from "./Shops";
import UserService from "./User";
import TagService from "./Tag";
import CommentsService from "./Comments";
import ProductsService from "./Products";
import ConfigurationService from "./Configuration";
import ShopServices from "./ShopServices";

exports.CategoryService = CategoryService;
exports.SessionService = SessionService;
exports.OpenIdService = OpenIdService;
exports.ShopsService = ShopsService;
exports.UserService = UserService;
exports.TagService = TagService;
exports.CommentsService = CommentsService;
exports.ProductsService = ProductsService;
exports.ConfigurationService = ConfigurationService;
exports.ShopServices = ShopServices;
