import CategoryService from "./Category";
import SessionService from "./Session";
import OpenIdService from "./OpenId";
import ShopsService from "./Shops";
import UserService from "./User";
import TagService from "./Tag";
import CommentsService from "./Comments";
import ProductsService from "./Products";
import ConfigurationService from "./Configuration";
import ShopServices from "./ShopServices";
import ClientService from './ClientService';
import GoogleMapService from './GoogleMap';
import NotificationService from './Notification';
import AuthenticateService from './Authenticate';
import MessageService from './Messages';
import OrdersService from './Orders';
import DhlService from './Dhl';
import UpsService from './Ups';
import PaypalService from './Paypal';
import WebsiteService from './Website';

exports.CategoryService = CategoryService;
exports.SessionService = SessionService;
exports.OpenIdService = OpenIdService;
exports.ShopsService = ShopsService;
exports.UserService = UserService;
exports.TagService = TagService;
exports.CommentsService = CommentsService;
exports.ProductsService = ProductsService;
exports.ConfigurationService = ConfigurationService;
exports.ShopServices = ShopServices;
exports.ClientService = ClientService;
exports.GoogleMapService = GoogleMapService;
exports.NotificationService = NotificationService;
exports.AuthenticateService = AuthenticateService;
exports.MessageService = MessageService;
exports.OrdersService = OrdersService;
exports.DhlService = DhlService;
exports.UpsService = UpsService;
exports.PaypalService = PaypalService;
exports.WebsiteService = WebsiteService;
