'use strict';

module.exports = {
    ClientId: 'website',
    ClientSecret: 'website',
    loginUrl: 'http://localhost:3003/login', // Website api definitions.
    googleMapUrl: 'https://maps.googleapis.com/maps/api',
    googleMapKey: 'AIzaSyBN72d3ipuyzbqhJgjwav5HnnKkLqp3KCU',
    apiUrl: 'http://localhost:5000',
    openIdUrl: 'http://localhost:5001',
    maxPackageSize: {
      length: 50,
      width: 80,
      height: 35
    },
    events: {
      USER_LOGGED_IN: 'USER_LOGGED_IN',
      USER_LOGGED_OUT: 'USER_LOGGED_OUT',
      UPDATE_SHOP: 'UPDATE_SHOP',
      NEW_PRODUCT: 'NEW_PRODUCT',
      NEW_SERVICE: 'NEW_SERVICE',
      EDIT_SHOP_LOADED: 'EDIT_SHOP_LOADED', // Loaded
      EDIT_USER_LOADED: 'EDIT_USER_LOADED',
      ADD_PRODUCT_LOADED: 'ADD_PRODUCT_LOADED',
      BASKET_LOADED: "BASKET_LOADED",
      EDIT_PRODUCT_LOADED: 'EDIT_PRODUCT_LOADED',
      PRINT_ORDER_LABEL_LOADED: 'PRINT_ORDER_LABEL_LOADED',
      EDIT_SERVICE_LOADED: 'EDIT_SERVICE_LOADED',
      UPDATE_SHOP_INFORMATION_ACT: 'UPDATE_SHOP_INFORMATION_ACT', // Actions performed on the website.
      UPDATE_USER_INFORMATION_ACT: 'UPDATE_USER_INFORMATION_ACT',
      UPDATE_BASKET_INFORMATION_ACT: 'UPDATE_BASKET_INFORMATION_ACT',
      UPDATE_ORDER_LABEL_ACT: 'UPDATE_ORDER_LABEL_ACT',
      SELECT_ORDER_ACT: 'SELECT_ORDER_ACT',
      SET_LABEL_PAYMENT_ACT: 'SET_LABEL_PAYMENT_ACT',
      VIEW_PRODUCT_ACT: 'VIEW_PRODUCT_ACT',
      EDIT_PRODUCT_ACT: 'EDIT_PRODUCT_ACT',
      VIEW_SERVICE_ACT: 'VIEW_SERVICE_ACT',
      EDIT_SERVICE_ACT: 'EDIT_SERVICE_ACT',
      UPDATE_PRODUCT_INFORMATION_ACT: 'UPDATE_PRODUCT_INFORMATION_ACT',
      UPDATE_SERVICE_INFORMATION_ACT: 'UPDATE_SERVICE_INFORMATION_ACT',
      NEW_SHOP_COMMENT_ARRIVED: 'NEW_SHOP_COMMENT_ARRIVED', // signalr events.
      REMOVE_SHOP_COMMENT_ARRIVED: 'REMOVE_SHOP_COMMENT_ARRIVED',
      SHOP_UPDATE_ARRIVED: "SHOP_UPDATE_ARRIVED",
      NEW_PRODUCT_COMMENT_ARRIVED: "NEW_PRODUCT_COMMENT_ARRIVED",
      REMOVE_PRODUCT_COMMENT_ARRIVED: "REMOVE_PRODUCT_COMMENT_ARRIVED",
      NEW_SERVICE_COMMENT_ARRIVED: "NEW_SERVICE_COMMENT_ARRIVED",
      REMOVE_SERVICE_COMMENT_ARRIVED: "REMOVE_SERVICE_COMMENT_ARRIVED",
      REMOVE_SHOP_ARRIVED: "REMOVE_SHOP_ARRIVED",
      REMOVE_CLIENT_SERVICE_ARRIVED: "REMOVE_CLIENT_SERVICE_ARRIVED",
      MESSAGE_ADDED: "MESSAGE_ADDED",
      ADD_CLIENT_SERVICE_ARRIVED: "ADD_CLIENT_SERVICE_ARRIVED",
      NEW_SHOP_SERVICE_ARRIVED: "NEW_SHOP_SERVICE_ARRIVED",
      ADD_PRODUCT_ARRIVED: "ADD_PRODUCT_ARRIVED",
      ORDER_UPDATED_ARRIVED: "ORDER_UPDATED_ARRIVED",
      ORDER_REMOVED_ARRIVED: "ORDER_REMOVED_ARRIVED",
      ORDER_ADDED_ARRIVED: "ORDER_ADDED_ARRIVED",
      NOTIFICATION_UPDATED_ARRIVED: "NOTIFICATION_UPDATED_ARRIVED",
      NOTIFICATION_ADDED_ARRIVED: "NOTIFICATION_ADDED_ARRIVED",
      ORDER_CONFIRMED_ARRIVED: "ORDER_CONFIRMED_ARRIVED",
      ORDER_RECEIVED_ARRIVED: "ORDER_RECEIVED_ARRIVED",
      ORDER_TRANSACTION_APPROVED_ARRIVED: "ORDER_TRANSACTION_APPROVED_ARRIVED",
      ORDER_LABEL_PURCHASED_ARRIVED: "ORDER_LABEL_PURCHASED_ARRIVED",
      UPDATE_PRODUCT_ARRIVED: "UPDATE_PRODUCT_ARRIVED",
      SERVICE_UPDATE_ARRIVED: "SERVICE_UPDATE_ARRIVED",
      SERVICE_REMOVE_ARRIVED: "SERVICE_REMOVE_ARRIVED",
      PRODUCT_REMOVE_ARRIVED: "PRODUCT_REMOVE_ARRIVED"
    }
};
